name: Setup Development Infrastructure
description: Logs into the GitHub container registry and checks out cheetah development infrastructure

inputs:
  PAT:
    description: A personal access token for logging into GitHub container registry and cloning cheetah development infrastructure
    required: true

runs:
  using: composite
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3.0.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.PAT }}

    - name: Checkout trifork/cheetah-development-infrastructure
      uses: actions/checkout@v4
      with:
        repository: trifork/cheetah-development-infrastructure
        token: ${{ github.token }}
        path: integrationtests
        branch: v1.1.0