// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Cheetah.ComponentTest.Test.Model.Avro
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class AvroObjectWithEnum : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""AvroObjectWithEnum"",""namespace"":""Cheetah.ComponentTest.Test.Model.Avro"",""fields"":[{""name"":""EnumType"",""type"":{""type"":""enum"",""name"":""EnumTypeAvro"",""namespace"":""Cheetah.ComponentTest.Test.Model.Avro"",""symbols"":[""EnumType1"",""EnumType2"",""EnumType3""]}},{""name"":""NullableInt"",""default"":null,""type"":[""null"",""int""]},{""name"":""NullableString"",""default"":null,""type"":[""null"",""string""]}]}");
		private EnumTypeAvro _EnumType;
		private System.Nullable<System.Int32> _NullableInt;
		private string _NullableString;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return AvroObjectWithEnum._SCHEMA;
			}
		}
		public EnumTypeAvro EnumType
		{
			get
			{
				return this._EnumType;
			}
			set
			{
				this._EnumType = value;
			}
		}
		public System.Nullable<System.Int32> NullableInt
		{
			get
			{
				return this._NullableInt;
			}
			set
			{
				this._NullableInt = value;
			}
		}
		public string NullableString
		{
			get
			{
				return this._NullableString;
			}
			set
			{
				this._NullableString = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.EnumType;
			case 1: return this.NullableInt;
			case 2: return this.NullableString;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			}
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.EnumType = (EnumTypeAvro)fieldValue; break;
			case 1: this.NullableInt = (System.Nullable<System.Int32>)fieldValue; break;
			case 2: this.NullableString = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
