// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Cheetah.Kafka.Test.TestModels.Avro
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class SimpleAvroObject : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"SimpleAvroObject\",\"namespace\":\"Cheetah.Kafka.Test.TestModels.Avro\",\"fields\":[{\"name\":\"Name\",\"type\":\"string\"},{\"name\":\"Number\",\"type\"" +
				":\"int\"}]}");
		private string _Name;
		private int _Number;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return SimpleAvroObject._SCHEMA;
			}
		}
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				this._Name = value;
			}
		}
		public int Number
		{
			get
			{
				return this._Number;
			}
			set
			{
				this._Number = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Name;
			case 1: return this.Number;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			}
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Name = (System.String)fieldValue; break;
			case 1: this.Number = (System.Int32)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			}
		}
	}
}
