name: "docfx build"
description: "sets up dotnet and builds docfx - requires checkout"

runs:
  using: composite
  steps:
    - name: Setup dot Net
      uses: actions/setup-dotnet@v5.0.0
      with:
        dotnet-version: "8.0"

    - name: Build docfx
      shell: bash
      run: |
        dotnet tool update -g docfx 
        docfx --warningsAsErrors docs/docfx.json