### YamlMime:ManagedReference
items:
- uid: Cheetah.Auth.Configuration.OAuth2Config
  commentId: T:Cheetah.Auth.Configuration.OAuth2Config
  id: OAuth2Config
  parent: Cheetah.Auth.Configuration
  children:
  - Cheetah.Auth.Configuration.OAuth2Config.ClientId
  - Cheetah.Auth.Configuration.OAuth2Config.ClientSecret
  - Cheetah.Auth.Configuration.OAuth2Config.EarlyExpiry
  - Cheetah.Auth.Configuration.OAuth2Config.EarlyRefresh
  - Cheetah.Auth.Configuration.OAuth2Config.RetryInterval
  - Cheetah.Auth.Configuration.OAuth2Config.Scope
  - Cheetah.Auth.Configuration.OAuth2Config.TokenEndpoint
  - Cheetah.Auth.Configuration.OAuth2Config.Validate
  langs:
  - csharp
  - vb
  name: OAuth2Config
  nameWithType: OAuth2Config
  fullName: Cheetah.Auth.Configuration.OAuth2Config
  type: Class
  source:
    remote:
      path: src/Cheetah.Auth/Configuration/OAuth2Config.cs
      branch: main
      repo: https://github.com/KastTrifork/cheetah-lib-shared-dotnet
    id: OAuth2Config
    path: ../src/Cheetah.Auth/Configuration/OAuth2Config.cs
    startLine: 8
  assemblies:
  - Cheetah.Auth
  namespace: Cheetah.Auth.Configuration
  summary: Configuration for OAuth2 authentication
  example: []
  syntax:
    content: public class OAuth2Config
    content.vb: Public Class OAuth2Config
  inheritance:
  - System.Object
- uid: Cheetah.Auth.Configuration.OAuth2Config.TokenEndpoint
  commentId: P:Cheetah.Auth.Configuration.OAuth2Config.TokenEndpoint
  id: TokenEndpoint
  parent: Cheetah.Auth.Configuration.OAuth2Config
  langs:
  - csharp
  - vb
  name: TokenEndpoint
  nameWithType: OAuth2Config.TokenEndpoint
  fullName: Cheetah.Auth.Configuration.OAuth2Config.TokenEndpoint
  type: Property
  source:
    remote:
      path: src/Cheetah.Auth/Configuration/OAuth2Config.cs
      branch: main
      repo: https://github.com/KastTrifork/cheetah-lib-shared-dotnet
    id: TokenEndpoint
    path: ../src/Cheetah.Auth/Configuration/OAuth2Config.cs
    startLine: 13
  assemblies:
  - Cheetah.Auth
  namespace: Cheetah.Auth.Configuration
  summary: The endpoint to retrieve the token from
  example: []
  syntax:
    content: >-
      [Required]

      public string TokenEndpoint { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: >-
      <Required>

      Public Property TokenEndpoint As String
  overload: Cheetah.Auth.Configuration.OAuth2Config.TokenEndpoint*
  attributes:
  - type: System.ComponentModel.DataAnnotations.RequiredAttribute
    ctor: System.ComponentModel.DataAnnotations.RequiredAttribute.#ctor
    arguments: []
- uid: Cheetah.Auth.Configuration.OAuth2Config.ClientId
  commentId: P:Cheetah.Auth.Configuration.OAuth2Config.ClientId
  id: ClientId
  parent: Cheetah.Auth.Configuration.OAuth2Config
  langs:
  - csharp
  - vb
  name: ClientId
  nameWithType: OAuth2Config.ClientId
  fullName: Cheetah.Auth.Configuration.OAuth2Config.ClientId
  type: Property
  source:
    remote:
      path: src/Cheetah.Auth/Configuration/OAuth2Config.cs
      branch: main
      repo: https://github.com/KastTrifork/cheetah-lib-shared-dotnet
    id: ClientId
    path: ../src/Cheetah.Auth/Configuration/OAuth2Config.cs
    startLine: 20
  assemblies:
  - Cheetah.Auth
  namespace: Cheetah.Auth.Configuration
  summary: The client id to use when authenticating
  example: []
  syntax:
    content: >-
      [Required]

      public string ClientId { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: >-
      <Required>

      Public Property ClientId As String
  overload: Cheetah.Auth.Configuration.OAuth2Config.ClientId*
  attributes:
  - type: System.ComponentModel.DataAnnotations.RequiredAttribute
    ctor: System.ComponentModel.DataAnnotations.RequiredAttribute.#ctor
    arguments: []
- uid: Cheetah.Auth.Configuration.OAuth2Config.ClientSecret
  commentId: P:Cheetah.Auth.Configuration.OAuth2Config.ClientSecret
  id: ClientSecret
  parent: Cheetah.Auth.Configuration.OAuth2Config
  langs:
  - csharp
  - vb
  name: ClientSecret
  nameWithType: OAuth2Config.ClientSecret
  fullName: Cheetah.Auth.Configuration.OAuth2Config.ClientSecret
  type: Property
  source:
    remote:
      path: src/Cheetah.Auth/Configuration/OAuth2Config.cs
      branch: main
      repo: https://github.com/KastTrifork/cheetah-lib-shared-dotnet
    id: ClientSecret
    path: ../src/Cheetah.Auth/Configuration/OAuth2Config.cs
    startLine: 27
  assemblies:
  - Cheetah.Auth
  namespace: Cheetah.Auth.Configuration
  summary: The client secret to use when authenticating
  example: []
  syntax:
    content: >-
      [Required]

      public string ClientSecret { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: >-
      <Required>

      Public Property ClientSecret As String
  overload: Cheetah.Auth.Configuration.OAuth2Config.ClientSecret*
  attributes:
  - type: System.ComponentModel.DataAnnotations.RequiredAttribute
    ctor: System.ComponentModel.DataAnnotations.RequiredAttribute.#ctor
    arguments: []
- uid: Cheetah.Auth.Configuration.OAuth2Config.Scope
  commentId: P:Cheetah.Auth.Configuration.OAuth2Config.Scope
  id: Scope
  parent: Cheetah.Auth.Configuration.OAuth2Config
  langs:
  - csharp
  - vb
  name: Scope
  nameWithType: OAuth2Config.Scope
  fullName: Cheetah.Auth.Configuration.OAuth2Config.Scope
  type: Property
  source:
    remote:
      path: src/Cheetah.Auth/Configuration/OAuth2Config.cs
      branch: main
      repo: https://github.com/KastTrifork/cheetah-lib-shared-dotnet
    id: Scope
    path: ../src/Cheetah.Auth/Configuration/OAuth2Config.cs
    startLine: 33
  assemblies:
  - Cheetah.Auth
  namespace: Cheetah.Auth.Configuration
  summary: Optional scope to request when authenticating
  example: []
  syntax:
    content: public string? Scope { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Scope As String
  overload: Cheetah.Auth.Configuration.OAuth2Config.Scope*
- uid: Cheetah.Auth.Configuration.OAuth2Config.RetryInterval
  commentId: P:Cheetah.Auth.Configuration.OAuth2Config.RetryInterval
  id: RetryInterval
  parent: Cheetah.Auth.Configuration.OAuth2Config
  langs:
  - csharp
  - vb
  name: RetryInterval
  nameWithType: OAuth2Config.RetryInterval
  fullName: Cheetah.Auth.Configuration.OAuth2Config.RetryInterval
  type: Property
  source:
    remote:
      path: src/Cheetah.Auth/Configuration/OAuth2Config.cs
      branch: main
      repo: https://github.com/KastTrifork/cheetah-lib-shared-dotnet
    id: RetryInterval
    path: ../src/Cheetah.Auth/Configuration/OAuth2Config.cs
    startLine: 38
  assemblies:
  - Cheetah.Auth
  namespace: Cheetah.Auth.Configuration
  summary: The interval between retry attempts to get a token
  example: []
  syntax:
    content: public TimeSpan RetryInterval { get; set; }
    parameters: []
    return:
      type: System.TimeSpan
    content.vb: Public Property RetryInterval As TimeSpan
  overload: Cheetah.Auth.Configuration.OAuth2Config.RetryInterval*
- uid: Cheetah.Auth.Configuration.OAuth2Config.EarlyRefresh
  commentId: P:Cheetah.Auth.Configuration.OAuth2Config.EarlyRefresh
  id: EarlyRefresh
  parent: Cheetah.Auth.Configuration.OAuth2Config
  langs:
  - csharp
  - vb
  name: EarlyRefresh
  nameWithType: OAuth2Config.EarlyRefresh
  fullName: Cheetah.Auth.Configuration.OAuth2Config.EarlyRefresh
  type: Property
  source:
    remote:
      path: src/Cheetah.Auth/Configuration/OAuth2Config.cs
      branch: main
      repo: https://github.com/KastTrifork/cheetah-lib-shared-dotnet
    id: EarlyRefresh
    path: ../src/Cheetah.Auth/Configuration/OAuth2Config.cs
    startLine: 43
  assemblies:
  - Cheetah.Auth
  namespace: Cheetah.Auth.Configuration
  summary: The time before the token's actual expiry when it should be refreshed.
  example: []
  syntax:
    content: public TimeSpan EarlyRefresh { get; set; }
    parameters: []
    return:
      type: System.TimeSpan
    content.vb: Public Property EarlyRefresh As TimeSpan
  overload: Cheetah.Auth.Configuration.OAuth2Config.EarlyRefresh*
- uid: Cheetah.Auth.Configuration.OAuth2Config.EarlyExpiry
  commentId: P:Cheetah.Auth.Configuration.OAuth2Config.EarlyExpiry
  id: EarlyExpiry
  parent: Cheetah.Auth.Configuration.OAuth2Config
  langs:
  - csharp
  - vb
  name: EarlyExpiry
  nameWithType: OAuth2Config.EarlyExpiry
  fullName: Cheetah.Auth.Configuration.OAuth2Config.EarlyExpiry
  type: Property
  source:
    remote:
      path: src/Cheetah.Auth/Configuration/OAuth2Config.cs
      branch: main
      repo: https://github.com/KastTrifork/cheetah-lib-shared-dotnet
    id: EarlyExpiry
    path: ../src/Cheetah.Auth/Configuration/OAuth2Config.cs
    startLine: 48
  assemblies:
  - Cheetah.Auth
  namespace: Cheetah.Auth.Configuration
  summary: The time before the token's actual expiry when it should be considered expired.
  example: []
  syntax:
    content: public TimeSpan EarlyExpiry { get; set; }
    parameters: []
    return:
      type: System.TimeSpan
    content.vb: Public Property EarlyExpiry As TimeSpan
  overload: Cheetah.Auth.Configuration.OAuth2Config.EarlyExpiry*
- uid: Cheetah.Auth.Configuration.OAuth2Config.Validate
  commentId: M:Cheetah.Auth.Configuration.OAuth2Config.Validate
  id: Validate
  parent: Cheetah.Auth.Configuration.OAuth2Config
  langs:
  - csharp
  - vb
  name: Validate()
  nameWithType: OAuth2Config.Validate()
  fullName: Cheetah.Auth.Configuration.OAuth2Config.Validate()
  type: Method
  source:
    remote:
      path: src/Cheetah.Auth/Configuration/OAuth2Config.cs
      branch: main
      repo: https://github.com/KastTrifork/cheetah-lib-shared-dotnet
    id: Validate
    path: ../src/Cheetah.Auth/Configuration/OAuth2Config.cs
    startLine: 54
  assemblies:
  - Cheetah.Auth
  namespace: Cheetah.Auth.Configuration
  summary: Validates that configuration has minimum values
  example: []
  syntax:
    content: public void Validate()
    content.vb: Public Sub Validate()
  overload: Cheetah.Auth.Configuration.OAuth2Config.Validate*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: ''
references:
- uid: Cheetah.Auth.Configuration
  commentId: N:Cheetah.Auth.Configuration
  href: Cheetah.html
  name: Cheetah.Auth.Configuration
  nameWithType: Cheetah.Auth.Configuration
  fullName: Cheetah.Auth.Configuration
  spec.csharp:
  - uid: Cheetah
    name: Cheetah
    href: Cheetah.html
  - name: .
  - uid: Cheetah.Auth
    name: Auth
    href: Cheetah.Auth.html
  - name: .
  - uid: Cheetah.Auth.Configuration
    name: Configuration
    href: Cheetah.Auth.Configuration.html
  spec.vb:
  - uid: Cheetah
    name: Cheetah
    href: Cheetah.html
  - name: .
  - uid: Cheetah.Auth
    name: Auth
    href: Cheetah.Auth.html
  - name: .
  - uid: Cheetah.Auth.Configuration
    name: Configuration
    href: Cheetah.Auth.Configuration.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Cheetah.Auth.Configuration.OAuth2Config.TokenEndpoint*
  commentId: Overload:Cheetah.Auth.Configuration.OAuth2Config.TokenEndpoint
  href: Cheetah.Auth.Configuration.OAuth2Config.html#Cheetah_Auth_Configuration_OAuth2Config_TokenEndpoint
  name: TokenEndpoint
  nameWithType: OAuth2Config.TokenEndpoint
  fullName: Cheetah.Auth.Configuration.OAuth2Config.TokenEndpoint
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Cheetah.Auth.Configuration.OAuth2Config.ClientId*
  commentId: Overload:Cheetah.Auth.Configuration.OAuth2Config.ClientId
  href: Cheetah.Auth.Configuration.OAuth2Config.html#Cheetah_Auth_Configuration_OAuth2Config_ClientId
  name: ClientId
  nameWithType: OAuth2Config.ClientId
  fullName: Cheetah.Auth.Configuration.OAuth2Config.ClientId
- uid: Cheetah.Auth.Configuration.OAuth2Config.ClientSecret*
  commentId: Overload:Cheetah.Auth.Configuration.OAuth2Config.ClientSecret
  href: Cheetah.Auth.Configuration.OAuth2Config.html#Cheetah_Auth_Configuration_OAuth2Config_ClientSecret
  name: ClientSecret
  nameWithType: OAuth2Config.ClientSecret
  fullName: Cheetah.Auth.Configuration.OAuth2Config.ClientSecret
- uid: Cheetah.Auth.Configuration.OAuth2Config.Scope*
  commentId: Overload:Cheetah.Auth.Configuration.OAuth2Config.Scope
  href: Cheetah.Auth.Configuration.OAuth2Config.html#Cheetah_Auth_Configuration_OAuth2Config_Scope
  name: Scope
  nameWithType: OAuth2Config.Scope
  fullName: Cheetah.Auth.Configuration.OAuth2Config.Scope
- uid: Cheetah.Auth.Configuration.OAuth2Config.RetryInterval*
  commentId: Overload:Cheetah.Auth.Configuration.OAuth2Config.RetryInterval
  href: Cheetah.Auth.Configuration.OAuth2Config.html#Cheetah_Auth_Configuration_OAuth2Config_RetryInterval
  name: RetryInterval
  nameWithType: OAuth2Config.RetryInterval
  fullName: Cheetah.Auth.Configuration.OAuth2Config.RetryInterval
- uid: System.TimeSpan
  commentId: T:System.TimeSpan
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.timespan
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: Cheetah.Auth.Configuration.OAuth2Config.EarlyRefresh*
  commentId: Overload:Cheetah.Auth.Configuration.OAuth2Config.EarlyRefresh
  href: Cheetah.Auth.Configuration.OAuth2Config.html#Cheetah_Auth_Configuration_OAuth2Config_EarlyRefresh
  name: EarlyRefresh
  nameWithType: OAuth2Config.EarlyRefresh
  fullName: Cheetah.Auth.Configuration.OAuth2Config.EarlyRefresh
- uid: Cheetah.Auth.Configuration.OAuth2Config.EarlyExpiry*
  commentId: Overload:Cheetah.Auth.Configuration.OAuth2Config.EarlyExpiry
  href: Cheetah.Auth.Configuration.OAuth2Config.html#Cheetah_Auth_Configuration_OAuth2Config_EarlyExpiry
  name: EarlyExpiry
  nameWithType: OAuth2Config.EarlyExpiry
  fullName: Cheetah.Auth.Configuration.OAuth2Config.EarlyExpiry
- uid: System.ArgumentException
  commentId: T:System.ArgumentException
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.argumentexception
  name: ArgumentException
  nameWithType: ArgumentException
  fullName: System.ArgumentException
- uid: Cheetah.Auth.Configuration.OAuth2Config.Validate*
  commentId: Overload:Cheetah.Auth.Configuration.OAuth2Config.Validate
  href: Cheetah.Auth.Configuration.OAuth2Config.html#Cheetah_Auth_Configuration_OAuth2Config_Validate
  name: Validate
  nameWithType: OAuth2Config.Validate
  fullName: Cheetah.Auth.Configuration.OAuth2Config.Validate
