---
version: "2.1"

services:
  zoo:
    image: quay.io/strimzi/kafka:0.33.2-kafka-3.2.3
    hostname: zoo
    profiles:
      - kafka
    command:
      ["sh", "-c", "bin/zookeeper-server-start.sh config/zookeeper.properties"]
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      LOG_DIR: /tmp/logs
    mem_limit: 512m

  kafka:
    image: ghcr.io/trifork/cheetah-infrastructure-utils-kafka:1.0.2
    hostname: kafka
    mem_limit: 1024m
    ports:
      - 19093:19093
    command:
      [
        "sh",
        "-c",
        "bin/kafka-server-start.sh /opt/kafka/custom-config/server.properties",
      ]
    profiles:
      - kafka
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_LOG4J_LOGGERS: "kafka.controller=WARN,kafka.producer.async.DefaultEventHandler=WARN,state.change.logger=WARN"
    volumes:
      - ./kafka.properties:/opt/kafka/custom-config/server.properties
    depends_on:
      zoo:
        condition: service_started
      cheetah.oauth.simulator:
        condition: service_healthy
    healthcheck:
      test: nc -z kafka 19093 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10

  opensearch:
    ports:
      - 9200:9200
    profiles:
      - opensearch
    environment:
      - cluster.name=opensearch-cluster
      - node.name=os01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - DISABLE_INSTALL_DEMO_CONFIG=false
      - network.host=0.0.0.0
      - plugins.security.ssl.http.enabled=false
    volumes:
      - "./opensearch_security.config.yml:/usr/share/opensearch/config/opensearch-security/config.yml"
    network_mode: cheetah-infrastructure
    hostname: opensearch
    image: "opensearchproject/opensearch:2.6.0"

  cheetah.oauth.simulator:
    hostname: cheetahoauthsimulator
    network_mode: cheetah-infrastructure
    image: ghcr.io/trifork/cheetah-oauth-simulator:latest
    ports:
      - 80:80
    environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      - OAuth__Mode=Asymmetric
      - "Simulator__DefaultRole=admin"

networks:
  default:
    name: "cheetah-infrastructure"
