### YamlMime:ManagedReference
items:
- uid: Cheetah.OpenSearch.Configuration.OpenSearchConfig.OpenSearchAuthMode
  commentId: T:Cheetah.OpenSearch.Configuration.OpenSearchConfig.OpenSearchAuthMode
  id: OpenSearchConfig.OpenSearchAuthMode
  parent: Cheetah.OpenSearch.Configuration
  children:
  - Cheetah.OpenSearch.Configuration.OpenSearchConfig.OpenSearchAuthMode.Basic
  - Cheetah.OpenSearch.Configuration.OpenSearchConfig.OpenSearchAuthMode.None
  - Cheetah.OpenSearch.Configuration.OpenSearchConfig.OpenSearchAuthMode.OAuth2
  langs:
  - csharp
  - vb
  name: OpenSearchConfig.OpenSearchAuthMode
  nameWithType: OpenSearchConfig.OpenSearchAuthMode
  fullName: Cheetah.OpenSearch.Configuration.OpenSearchConfig.OpenSearchAuthMode
  type: Enum
  source:
    remote:
      path: src/Cheetah.OpenSearch/Configuration/OpenSearchConfig.cs
      branch: main
      repo: https://github.com/trifork/cheetah-lib-shared-dotnet
    id: OpenSearchAuthMode
    path: ../src/Cheetah.OpenSearch/Configuration/OpenSearchConfig.cs
    startLine: 83
  assemblies:
  - Cheetah.OpenSearch
  namespace: Cheetah.OpenSearch.Configuration
  summary: Authentication method to use when connecting to OpenSearch
  example: []
  syntax:
    content: public enum OpenSearchConfig.OpenSearchAuthMode
    content.vb: Public Enum OpenSearchConfig.OpenSearchAuthMode
- uid: Cheetah.OpenSearch.Configuration.OpenSearchConfig.OpenSearchAuthMode.None
  commentId: F:Cheetah.OpenSearch.Configuration.OpenSearchConfig.OpenSearchAuthMode.None
  id: None
  parent: Cheetah.OpenSearch.Configuration.OpenSearchConfig.OpenSearchAuthMode
  langs:
  - csharp
  - vb
  name: None
  nameWithType: OpenSearchConfig.OpenSearchAuthMode.None
  fullName: Cheetah.OpenSearch.Configuration.OpenSearchConfig.OpenSearchAuthMode.None
  type: Field
  source:
    remote:
      path: src/Cheetah.OpenSearch/Configuration/OpenSearchConfig.cs
      branch: main
      repo: https://github.com/trifork/cheetah-lib-shared-dotnet
    id: None
    path: ../src/Cheetah.OpenSearch/Configuration/OpenSearchConfig.cs
    startLine: 88
  assemblies:
  - Cheetah.OpenSearch
  namespace: Cheetah.OpenSearch.Configuration
  summary: No authentication
  example: []
  syntax:
    content: None = 0
    return:
      type: Cheetah.OpenSearch.Configuration.OpenSearchConfig.OpenSearchAuthMode
- uid: Cheetah.OpenSearch.Configuration.OpenSearchConfig.OpenSearchAuthMode.Basic
  commentId: F:Cheetah.OpenSearch.Configuration.OpenSearchConfig.OpenSearchAuthMode.Basic
  id: Basic
  parent: Cheetah.OpenSearch.Configuration.OpenSearchConfig.OpenSearchAuthMode
  langs:
  - csharp
  - vb
  name: Basic
  nameWithType: OpenSearchConfig.OpenSearchAuthMode.Basic
  fullName: Cheetah.OpenSearch.Configuration.OpenSearchConfig.OpenSearchAuthMode.Basic
  type: Field
  source:
    remote:
      path: src/Cheetah.OpenSearch/Configuration/OpenSearchConfig.cs
      branch: main
      repo: https://github.com/trifork/cheetah-lib-shared-dotnet
    id: Basic
    path: ../src/Cheetah.OpenSearch/Configuration/OpenSearchConfig.cs
    startLine: 93
  assemblies:
  - Cheetah.OpenSearch
  namespace: Cheetah.OpenSearch.Configuration
  summary: Basic username/password authentication
  example: []
  syntax:
    content: Basic = 1
    return:
      type: Cheetah.OpenSearch.Configuration.OpenSearchConfig.OpenSearchAuthMode
- uid: Cheetah.OpenSearch.Configuration.OpenSearchConfig.OpenSearchAuthMode.OAuth2
  commentId: F:Cheetah.OpenSearch.Configuration.OpenSearchConfig.OpenSearchAuthMode.OAuth2
  id: OAuth2
  parent: Cheetah.OpenSearch.Configuration.OpenSearchConfig.OpenSearchAuthMode
  langs:
  - csharp
  - vb
  name: OAuth2
  nameWithType: OpenSearchConfig.OpenSearchAuthMode.OAuth2
  fullName: Cheetah.OpenSearch.Configuration.OpenSearchConfig.OpenSearchAuthMode.OAuth2
  type: Field
  source:
    remote:
      path: src/Cheetah.OpenSearch/Configuration/OpenSearchConfig.cs
      branch: main
      repo: https://github.com/trifork/cheetah-lib-shared-dotnet
    id: OAuth2
    path: ../src/Cheetah.OpenSearch/Configuration/OpenSearchConfig.cs
    startLine: 98
  assemblies:
  - Cheetah.OpenSearch
  namespace: Cheetah.OpenSearch.Configuration
  summary: OAuth2 token authentication
  example: []
  syntax:
    content: OAuth2 = 2
    return:
      type: Cheetah.OpenSearch.Configuration.OpenSearchConfig.OpenSearchAuthMode
references:
- uid: Cheetah.OpenSearch.Configuration
  commentId: N:Cheetah.OpenSearch.Configuration
  href: Cheetah.html
  name: Cheetah.OpenSearch.Configuration
  nameWithType: Cheetah.OpenSearch.Configuration
  fullName: Cheetah.OpenSearch.Configuration
  spec.csharp:
  - uid: Cheetah
    name: Cheetah
    href: Cheetah.html
  - name: .
  - uid: Cheetah.OpenSearch
    name: OpenSearch
    href: Cheetah.OpenSearch.html
  - name: .
  - uid: Cheetah.OpenSearch.Configuration
    name: Configuration
    href: Cheetah.OpenSearch.Configuration.html
  spec.vb:
  - uid: Cheetah
    name: Cheetah
    href: Cheetah.html
  - name: .
  - uid: Cheetah.OpenSearch
    name: OpenSearch
    href: Cheetah.OpenSearch.html
  - name: .
  - uid: Cheetah.OpenSearch.Configuration
    name: Configuration
    href: Cheetah.OpenSearch.Configuration.html
- uid: Cheetah.OpenSearch.Configuration.OpenSearchConfig.OpenSearchAuthMode
  commentId: T:Cheetah.OpenSearch.Configuration.OpenSearchConfig.OpenSearchAuthMode
  parent: Cheetah.OpenSearch.Configuration
  href: Cheetah.OpenSearch.Configuration.OpenSearchConfig.html
  name: OpenSearchConfig.OpenSearchAuthMode
  nameWithType: OpenSearchConfig.OpenSearchAuthMode
  fullName: Cheetah.OpenSearch.Configuration.OpenSearchConfig.OpenSearchAuthMode
  spec.csharp:
  - uid: Cheetah.OpenSearch.Configuration.OpenSearchConfig
    name: OpenSearchConfig
    href: Cheetah.OpenSearch.Configuration.OpenSearchConfig.html
  - name: .
  - uid: Cheetah.OpenSearch.Configuration.OpenSearchConfig.OpenSearchAuthMode
    name: OpenSearchAuthMode
    href: Cheetah.OpenSearch.Configuration.OpenSearchConfig.OpenSearchAuthMode.html
  spec.vb:
  - uid: Cheetah.OpenSearch.Configuration.OpenSearchConfig
    name: OpenSearchConfig
    href: Cheetah.OpenSearch.Configuration.OpenSearchConfig.html
  - name: .
  - uid: Cheetah.OpenSearch.Configuration.OpenSearchConfig.OpenSearchAuthMode
    name: OpenSearchAuthMode
    href: Cheetah.OpenSearch.Configuration.OpenSearchConfig.OpenSearchAuthMode.html
