---
- name: Cheetah.Kafka
  items:
    - name: latest
      href: Cheetah.Kafka/toc.yml
      homepage: Cheetah.Kafka/index.md
    - name: v2.1.0
      href: Cheetah.Kafka/v2.1.0/toc.yml
- name: Cheetah.Kafka
  items:
    - name: latest
      href: Cheetah.Kafka/toc.yml
      homepage: Cheetah.Kafka/index.md
    - name: v2.1.0
      href: Cheetah.Kafka/v2.1.0/toc.yml
- name: Cheetah.Kafka
  items:
    - name: latest
      href: Cheetah.Kafka/toc.yml
      homepage: Cheetah.Kafka/index.md
    - name: v2.1.0
      href: Cheetah.Kafka/v2.1.0/toc.yml
