---
- name: Cheetah.Kafka
  items:
    - name: v2.1
      href: Cheetah.Kafka/v2.1/toc.yml
- name: Cheetah.OpenSearch
  items:
    - name: v1.1
      href: Cheetah.OpenSearch/v1.1/toc.yml
- name: Cheetah.Auth
  href: Cheetah.Auth/index.md

