### YamlMime:ManagedReference
items:
- uid: Cheetah.Kafka.Configuration.KafkaConfig
  commentId: T:Cheetah.Kafka.Configuration.KafkaConfig
  id: KafkaConfig
  parent: Cheetah.Kafka.Configuration
  children:
  - Cheetah.Kafka.Configuration.KafkaConfig.GetClientConfig
  - Cheetah.Kafka.Configuration.KafkaConfig.OAuth2
  - Cheetah.Kafka.Configuration.KafkaConfig.Position
  - Cheetah.Kafka.Configuration.KafkaConfig.Principal
  - Cheetah.Kafka.Configuration.KafkaConfig.SaslMechanism
  - Cheetah.Kafka.Configuration.KafkaConfig.SecurityProtocol
  - Cheetah.Kafka.Configuration.KafkaConfig.SslCaLocation
  - Cheetah.Kafka.Configuration.KafkaConfig.Url
  - Cheetah.Kafka.Configuration.KafkaConfig.Validate
  langs:
  - csharp
  - vb
  name: KafkaConfig
  nameWithType: KafkaConfig
  fullName: Cheetah.Kafka.Configuration.KafkaConfig
  type: Class
  source:
    remote:
      path: src/Cheetah.Kafka/Configuration/KafkaConfig.cs
      branch: main
      repo: https://github.com/KastTrifork/cheetah-lib-shared-dotnet
    id: KafkaConfig
    path: ../src/Cheetah.Kafka/Configuration/KafkaConfig.cs
    startLine: 11
  assemblies:
  - Cheetah.Kafka
  namespace: Cheetah.Kafka.Configuration
  summary: KafkaConfig for IOptions
  example: []
  syntax:
    content: public class KafkaConfig
    content.vb: Public Class KafkaConfig
  inheritance:
  - System.Object
- uid: Cheetah.Kafka.Configuration.KafkaConfig.Position
  commentId: F:Cheetah.Kafka.Configuration.KafkaConfig.Position
  id: Position
  parent: Cheetah.Kafka.Configuration.KafkaConfig
  langs:
  - csharp
  - vb
  name: Position
  nameWithType: KafkaConfig.Position
  fullName: Cheetah.Kafka.Configuration.KafkaConfig.Position
  type: Field
  source:
    remote:
      path: src/Cheetah.Kafka/Configuration/KafkaConfig.cs
      branch: main
      repo: https://github.com/KastTrifork/cheetah-lib-shared-dotnet
    id: Position
    path: ../src/Cheetah.Kafka/Configuration/KafkaConfig.cs
    startLine: 16
  assemblies:
  - Cheetah.Kafka
  namespace: Cheetah.Kafka.Configuration
  summary: Prefix for options e.g. Kafka__
  example: []
  syntax:
    content: public const string Position = "Kafka"
    return:
      type: System.String
    content.vb: Public Const Position As String = "Kafka"
- uid: Cheetah.Kafka.Configuration.KafkaConfig.Url
  commentId: P:Cheetah.Kafka.Configuration.KafkaConfig.Url
  id: Url
  parent: Cheetah.Kafka.Configuration.KafkaConfig
  langs:
  - csharp
  - vb
  name: Url
  nameWithType: KafkaConfig.Url
  fullName: Cheetah.Kafka.Configuration.KafkaConfig.Url
  type: Property
  source:
    remote:
      path: src/Cheetah.Kafka/Configuration/KafkaConfig.cs
      branch: main
      repo: https://github.com/KastTrifork/cheetah-lib-shared-dotnet
    id: Url
    path: ../src/Cheetah.Kafka/Configuration/KafkaConfig.cs
    startLine: 22
  assemblies:
  - Cheetah.Kafka
  namespace: Cheetah.Kafka.Configuration
  summary: Bootstrap Url.
  example: []
  syntax:
    content: >-
      [Required]

      public string Url { get; set; }
    parameters: []
    return:
      type: System.String
      description: ''
    content.vb: >-
      <Required>

      Public Property Url As String
  overload: Cheetah.Kafka.Configuration.KafkaConfig.Url*
  attributes:
  - type: System.ComponentModel.DataAnnotations.RequiredAttribute
    ctor: System.ComponentModel.DataAnnotations.RequiredAttribute.#ctor
    arguments: []
- uid: Cheetah.Kafka.Configuration.KafkaConfig.Principal
  commentId: P:Cheetah.Kafka.Configuration.KafkaConfig.Principal
  id: Principal
  parent: Cheetah.Kafka.Configuration.KafkaConfig
  langs:
  - csharp
  - vb
  name: Principal
  nameWithType: KafkaConfig.Principal
  fullName: Cheetah.Kafka.Configuration.KafkaConfig.Principal
  type: Property
  source:
    remote:
      path: src/Cheetah.Kafka/Configuration/KafkaConfig.cs
      branch: main
      repo: https://github.com/KastTrifork/cheetah-lib-shared-dotnet
    id: Principal
    path: ../src/Cheetah.Kafka/Configuration/KafkaConfig.cs
    startLine: 28
  assemblies:
  - Cheetah.Kafka
  namespace: Cheetah.Kafka.Configuration
  summary: The principal used for authentication. Defaults to <code>unused</code> and is <i>usually</i> not required.
  example: []
  syntax:
    content: public string Principal { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Principal As String
  overload: Cheetah.Kafka.Configuration.KafkaConfig.Principal*
- uid: Cheetah.Kafka.Configuration.KafkaConfig.SecurityProtocol
  commentId: P:Cheetah.Kafka.Configuration.KafkaConfig.SecurityProtocol
  id: SecurityProtocol
  parent: Cheetah.Kafka.Configuration.KafkaConfig
  langs:
  - csharp
  - vb
  name: SecurityProtocol
  nameWithType: KafkaConfig.SecurityProtocol
  fullName: Cheetah.Kafka.Configuration.KafkaConfig.SecurityProtocol
  type: Property
  source:
    remote:
      path: src/Cheetah.Kafka/Configuration/KafkaConfig.cs
      branch: main
      repo: https://github.com/KastTrifork/cheetah-lib-shared-dotnet
    id: SecurityProtocol
    path: ../src/Cheetah.Kafka/Configuration/KafkaConfig.cs
    startLine: 33
  assemblies:
  - Cheetah.Kafka
  namespace: Cheetah.Kafka.Configuration
  summary: The security protocol used to communicate with brokers.
  example: []
  syntax:
    content: public SecurityProtocol SecurityProtocol { get; set; }
    parameters: []
    return:
      type: Confluent.Kafka.SecurityProtocol
    content.vb: Public Property SecurityProtocol As SecurityProtocol
  overload: Cheetah.Kafka.Configuration.KafkaConfig.SecurityProtocol*
- uid: Cheetah.Kafka.Configuration.KafkaConfig.SslCaLocation
  commentId: P:Cheetah.Kafka.Configuration.KafkaConfig.SslCaLocation
  id: SslCaLocation
  parent: Cheetah.Kafka.Configuration.KafkaConfig
  langs:
  - csharp
  - vb
  name: SslCaLocation
  nameWithType: KafkaConfig.SslCaLocation
  fullName: Cheetah.Kafka.Configuration.KafkaConfig.SslCaLocation
  type: Property
  source:
    remote:
      path: src/Cheetah.Kafka/Configuration/KafkaConfig.cs
      branch: main
      repo: https://github.com/KastTrifork/cheetah-lib-shared-dotnet
    id: SslCaLocation
    path: ../src/Cheetah.Kafka/Configuration/KafkaConfig.cs
    startLine: 38
  assemblies:
  - Cheetah.Kafka
  namespace: Cheetah.Kafka.Configuration
  summary: The location of the CA certificate file used to verify the broker's certificate.
  example: []
  syntax:
    content: public string SslCaLocation { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property SslCaLocation As String
  overload: Cheetah.Kafka.Configuration.KafkaConfig.SslCaLocation*
- uid: Cheetah.Kafka.Configuration.KafkaConfig.SaslMechanism
  commentId: P:Cheetah.Kafka.Configuration.KafkaConfig.SaslMechanism
  id: SaslMechanism
  parent: Cheetah.Kafka.Configuration.KafkaConfig
  langs:
  - csharp
  - vb
  name: SaslMechanism
  nameWithType: KafkaConfig.SaslMechanism
  fullName: Cheetah.Kafka.Configuration.KafkaConfig.SaslMechanism
  type: Property
  source:
    remote:
      path: src/Cheetah.Kafka/Configuration/KafkaConfig.cs
      branch: main
      repo: https://github.com/KastTrifork/cheetah-lib-shared-dotnet
    id: SaslMechanism
    path: ../src/Cheetah.Kafka/Configuration/KafkaConfig.cs
    startLine: 43
  assemblies:
  - Cheetah.Kafka
  namespace: Cheetah.Kafka.Configuration
  summary: The Sasl Mechanism used to communicate with brokers.
  example: []
  syntax:
    content: public SaslMechanism SaslMechanism { get; set; }
    parameters: []
    return:
      type: Confluent.Kafka.SaslMechanism
    content.vb: Public Property SaslMechanism As SaslMechanism
  overload: Cheetah.Kafka.Configuration.KafkaConfig.SaslMechanism*
- uid: Cheetah.Kafka.Configuration.KafkaConfig.OAuth2
  commentId: P:Cheetah.Kafka.Configuration.KafkaConfig.OAuth2
  id: OAuth2
  parent: Cheetah.Kafka.Configuration.KafkaConfig
  langs:
  - csharp
  - vb
  name: OAuth2
  nameWithType: KafkaConfig.OAuth2
  fullName: Cheetah.Kafka.Configuration.KafkaConfig.OAuth2
  type: Property
  source:
    remote:
      path: src/Cheetah.Kafka/Configuration/KafkaConfig.cs
      branch: main
      repo: https://github.com/KastTrifork/cheetah-lib-shared-dotnet
    id: OAuth2
    path: ../src/Cheetah.Kafka/Configuration/KafkaConfig.cs
    startLine: 48
  assemblies:
  - Cheetah.Kafka
  namespace: Cheetah.Kafka.Configuration
  summary: The OAuth2 configuration
  example: []
  syntax:
    content: public OAuth2Config OAuth2 { get; set; }
    parameters: []
    return:
      type: Cheetah.Auth.Configuration.OAuth2Config
    content.vb: Public Property OAuth2 As OAuth2Config
  overload: Cheetah.Kafka.Configuration.KafkaConfig.OAuth2*
- uid: Cheetah.Kafka.Configuration.KafkaConfig.Validate
  commentId: M:Cheetah.Kafka.Configuration.KafkaConfig.Validate
  id: Validate
  parent: Cheetah.Kafka.Configuration.KafkaConfig
  langs:
  - csharp
  - vb
  name: Validate()
  nameWithType: KafkaConfig.Validate()
  fullName: Cheetah.Kafka.Configuration.KafkaConfig.Validate()
  type: Method
  source:
    remote:
      path: src/Cheetah.Kafka/Configuration/KafkaConfig.cs
      branch: main
      repo: https://github.com/KastTrifork/cheetah-lib-shared-dotnet
    id: Validate
    path: ../src/Cheetah.Kafka/Configuration/KafkaConfig.cs
    startLine: 54
  assemblies:
  - Cheetah.Kafka
  namespace: Cheetah.Kafka.Configuration
  summary: Validates and throws an error if the configuration is invalid.
  example: []
  syntax:
    content: public void Validate()
    content.vb: Public Sub Validate()
  overload: Cheetah.Kafka.Configuration.KafkaConfig.Validate*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: Thrown if the configuration is invalid
- uid: Cheetah.Kafka.Configuration.KafkaConfig.GetClientConfig
  commentId: M:Cheetah.Kafka.Configuration.KafkaConfig.GetClientConfig
  id: GetClientConfig
  parent: Cheetah.Kafka.Configuration.KafkaConfig
  langs:
  - csharp
  - vb
  name: GetClientConfig()
  nameWithType: KafkaConfig.GetClientConfig()
  fullName: Cheetah.Kafka.Configuration.KafkaConfig.GetClientConfig()
  type: Method
  source:
    remote:
      path: src/Cheetah.Kafka/Configuration/KafkaConfig.cs
      branch: main
      repo: https://github.com/KastTrifork/cheetah-lib-shared-dotnet
    id: GetClientConfig
    path: ../src/Cheetah.Kafka/Configuration/KafkaConfig.cs
    startLine: 91
  assemblies:
  - Cheetah.Kafka
  namespace: Cheetah.Kafka.Configuration
  summary: Converts the configuration to a <xref href="Confluent.Kafka.ClientConfig" data-throw-if-not-resolved="false"></xref>/&gt;.
  example: []
  syntax:
    content: public ClientConfig GetClientConfig()
    return:
      type: Confluent.Kafka.ClientConfig
      description: The converted <xref href="Confluent.Kafka.ClientConfig" data-throw-if-not-resolved="false"></xref>
    content.vb: Public Function GetClientConfig() As ClientConfig
  overload: Cheetah.Kafka.Configuration.KafkaConfig.GetClientConfig*
references:
- uid: Cheetah.Kafka.Configuration
  commentId: N:Cheetah.Kafka.Configuration
  href: Cheetah.html
  name: Cheetah.Kafka.Configuration
  nameWithType: Cheetah.Kafka.Configuration
  fullName: Cheetah.Kafka.Configuration
  spec.csharp:
  - uid: Cheetah
    name: Cheetah
    href: Cheetah.html
  - name: .
  - uid: Cheetah.Kafka
    name: Kafka
    href: Cheetah.Kafka.html
  - name: .
  - uid: Cheetah.Kafka.Configuration
    name: Configuration
    href: Cheetah.Kafka.Configuration.html
  spec.vb:
  - uid: Cheetah
    name: Cheetah
    href: Cheetah.html
  - name: .
  - uid: Cheetah.Kafka
    name: Kafka
    href: Cheetah.Kafka.html
  - name: .
  - uid: Cheetah.Kafka.Configuration
    name: Configuration
    href: Cheetah.Kafka.Configuration.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Cheetah.Kafka.Configuration.KafkaConfig.Url*
  commentId: Overload:Cheetah.Kafka.Configuration.KafkaConfig.Url
  href: Cheetah.Kafka.Configuration.KafkaConfig.html#Cheetah_Kafka_Configuration_KafkaConfig_Url
  name: Url
  nameWithType: KafkaConfig.Url
  fullName: Cheetah.Kafka.Configuration.KafkaConfig.Url
- uid: Cheetah.Kafka.Configuration.KafkaConfig.Principal*
  commentId: Overload:Cheetah.Kafka.Configuration.KafkaConfig.Principal
  href: Cheetah.Kafka.Configuration.KafkaConfig.html#Cheetah_Kafka_Configuration_KafkaConfig_Principal
  name: Principal
  nameWithType: KafkaConfig.Principal
  fullName: Cheetah.Kafka.Configuration.KafkaConfig.Principal
- uid: Cheetah.Kafka.Configuration.KafkaConfig.SecurityProtocol*
  commentId: Overload:Cheetah.Kafka.Configuration.KafkaConfig.SecurityProtocol
  href: Cheetah.Kafka.Configuration.KafkaConfig.html#Cheetah_Kafka_Configuration_KafkaConfig_SecurityProtocol
  name: SecurityProtocol
  nameWithType: KafkaConfig.SecurityProtocol
  fullName: Cheetah.Kafka.Configuration.KafkaConfig.SecurityProtocol
- uid: Confluent.Kafka.SecurityProtocol
  commentId: T:Confluent.Kafka.SecurityProtocol
  parent: Confluent.Kafka
  isExternal: true
  name: SecurityProtocol
  nameWithType: SecurityProtocol
  fullName: Confluent.Kafka.SecurityProtocol
- uid: Confluent.Kafka
  commentId: N:Confluent.Kafka
  isExternal: true
  name: Confluent.Kafka
  nameWithType: Confluent.Kafka
  fullName: Confluent.Kafka
  spec.csharp:
  - uid: Confluent
    name: Confluent
    isExternal: true
  - name: .
  - uid: Confluent.Kafka
    name: Kafka
    isExternal: true
  spec.vb:
  - uid: Confluent
    name: Confluent
    isExternal: true
  - name: .
  - uid: Confluent.Kafka
    name: Kafka
    isExternal: true
- uid: Cheetah.Kafka.Configuration.KafkaConfig.SslCaLocation*
  commentId: Overload:Cheetah.Kafka.Configuration.KafkaConfig.SslCaLocation
  href: Cheetah.Kafka.Configuration.KafkaConfig.html#Cheetah_Kafka_Configuration_KafkaConfig_SslCaLocation
  name: SslCaLocation
  nameWithType: KafkaConfig.SslCaLocation
  fullName: Cheetah.Kafka.Configuration.KafkaConfig.SslCaLocation
- uid: Cheetah.Kafka.Configuration.KafkaConfig.SaslMechanism*
  commentId: Overload:Cheetah.Kafka.Configuration.KafkaConfig.SaslMechanism
  href: Cheetah.Kafka.Configuration.KafkaConfig.html#Cheetah_Kafka_Configuration_KafkaConfig_SaslMechanism
  name: SaslMechanism
  nameWithType: KafkaConfig.SaslMechanism
  fullName: Cheetah.Kafka.Configuration.KafkaConfig.SaslMechanism
- uid: Confluent.Kafka.SaslMechanism
  commentId: T:Confluent.Kafka.SaslMechanism
  parent: Confluent.Kafka
  isExternal: true
  name: SaslMechanism
  nameWithType: SaslMechanism
  fullName: Confluent.Kafka.SaslMechanism
- uid: Cheetah.Kafka.Configuration.KafkaConfig.OAuth2*
  commentId: Overload:Cheetah.Kafka.Configuration.KafkaConfig.OAuth2
  href: Cheetah.Kafka.Configuration.KafkaConfig.html#Cheetah_Kafka_Configuration_KafkaConfig_OAuth2
  name: OAuth2
  nameWithType: KafkaConfig.OAuth2
  fullName: Cheetah.Kafka.Configuration.KafkaConfig.OAuth2
- uid: Cheetah.Auth.Configuration.OAuth2Config
  commentId: T:Cheetah.Auth.Configuration.OAuth2Config
  parent: Cheetah.Auth.Configuration
  name: OAuth2Config
  nameWithType: OAuth2Config
  fullName: Cheetah.Auth.Configuration.OAuth2Config
- uid: Cheetah.Auth.Configuration
  commentId: N:Cheetah.Auth.Configuration
  name: Cheetah.Auth.Configuration
  nameWithType: Cheetah.Auth.Configuration
  fullName: Cheetah.Auth.Configuration
  spec.csharp:
  - uid: Cheetah
    name: Cheetah
  - name: .
  - uid: Cheetah.Auth
    name: Auth
  - name: .
  - uid: Cheetah.Auth.Configuration
    name: Configuration
  spec.vb:
  - uid: Cheetah
    name: Cheetah
  - name: .
  - uid: Cheetah.Auth
    name: Auth
  - name: .
  - uid: Cheetah.Auth.Configuration
    name: Configuration
- uid: System.ArgumentException
  commentId: T:System.ArgumentException
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.argumentexception
  name: ArgumentException
  nameWithType: ArgumentException
  fullName: System.ArgumentException
- uid: Cheetah.Kafka.Configuration.KafkaConfig.Validate*
  commentId: Overload:Cheetah.Kafka.Configuration.KafkaConfig.Validate
  href: Cheetah.Kafka.Configuration.KafkaConfig.html#Cheetah_Kafka_Configuration_KafkaConfig_Validate
  name: Validate
  nameWithType: KafkaConfig.Validate
  fullName: Cheetah.Kafka.Configuration.KafkaConfig.Validate
- uid: Confluent.Kafka.ClientConfig
  commentId: T:Confluent.Kafka.ClientConfig
  parent: Confluent.Kafka
  isExternal: true
  name: ClientConfig
  nameWithType: ClientConfig
  fullName: Confluent.Kafka.ClientConfig
- uid: Cheetah.Kafka.Configuration.KafkaConfig.GetClientConfig*
  commentId: Overload:Cheetah.Kafka.Configuration.KafkaConfig.GetClientConfig
  href: Cheetah.Kafka.Configuration.KafkaConfig.html#Cheetah_Kafka_Configuration_KafkaConfig_GetClientConfig
  name: GetClientConfig
  nameWithType: KafkaConfig.GetClientConfig
  fullName: Cheetah.Kafka.Configuration.KafkaConfig.GetClientConfig
