### YamlMime:ManagedReference
items:
- uid: Cheetah.OpenSearch.Configuration
  commentId: N:Cheetah.OpenSearch.Configuration
  id: Cheetah.OpenSearch.Configuration
  children:
  - Cheetah.OpenSearch.Configuration.OpenSearchConfig
  - Cheetah.OpenSearch.Configuration.OpenSearchConfig.OpenSearchAuthMode
  langs:
  - csharp
  - vb
  name: Cheetah.OpenSearch.Configuration
  nameWithType: Cheetah.OpenSearch.Configuration
  fullName: Cheetah.OpenSearch.Configuration
  type: Namespace
  assemblies:
  - Cheetah.OpenSearch
references:
- uid: Cheetah.OpenSearch.Configuration.OpenSearchConfig
  commentId: T:Cheetah.OpenSearch.Configuration.OpenSearchConfig
  parent: Cheetah.OpenSearch.Configuration
  href: Cheetah.OpenSearch.Configuration.OpenSearchConfig.html
  name: OpenSearchConfig
  nameWithType: OpenSearchConfig
  fullName: Cheetah.OpenSearch.Configuration.OpenSearchConfig
- uid: Cheetah.OpenSearch.Configuration.OpenSearchConfig.OpenSearchAuthMode
  commentId: T:Cheetah.OpenSearch.Configuration.OpenSearchConfig.OpenSearchAuthMode
  parent: Cheetah.OpenSearch.Configuration
  href: Cheetah.OpenSearch.Configuration.OpenSearchConfig.html
  name: OpenSearchConfig.OpenSearchAuthMode
  nameWithType: OpenSearchConfig.OpenSearchAuthMode
  fullName: Cheetah.OpenSearch.Configuration.OpenSearchConfig.OpenSearchAuthMode
  spec.csharp:
  - uid: Cheetah.OpenSearch.Configuration.OpenSearchConfig
    name: OpenSearchConfig
    href: Cheetah.OpenSearch.Configuration.OpenSearchConfig.html
  - name: .
  - uid: Cheetah.OpenSearch.Configuration.OpenSearchConfig.OpenSearchAuthMode
    name: OpenSearchAuthMode
    href: Cheetah.OpenSearch.Configuration.OpenSearchConfig.OpenSearchAuthMode.html
  spec.vb:
  - uid: Cheetah.OpenSearch.Configuration.OpenSearchConfig
    name: OpenSearchConfig
    href: Cheetah.OpenSearch.Configuration.OpenSearchConfig.html
  - name: .
  - uid: Cheetah.OpenSearch.Configuration.OpenSearchConfig.OpenSearchAuthMode
    name: OpenSearchAuthMode
    href: Cheetah.OpenSearch.Configuration.OpenSearchConfig.OpenSearchAuthMode.html
- uid: Cheetah.OpenSearch.Configuration
  commentId: N:Cheetah.OpenSearch.Configuration
  href: Cheetah.html
  name: Cheetah.OpenSearch.Configuration
  nameWithType: Cheetah.OpenSearch.Configuration
  fullName: Cheetah.OpenSearch.Configuration
  spec.csharp:
  - uid: Cheetah
    name: Cheetah
    href: Cheetah.html
  - name: .
  - uid: Cheetah.OpenSearch
    name: OpenSearch
    href: Cheetah.OpenSearch.html
  - name: .
  - uid: Cheetah.OpenSearch.Configuration
    name: Configuration
    href: Cheetah.OpenSearch.Configuration.html
  spec.vb:
  - uid: Cheetah
    name: Cheetah
    href: Cheetah.html
  - name: .
  - uid: Cheetah.OpenSearch
    name: OpenSearch
    href: Cheetah.OpenSearch.html
  - name: .
  - uid: Cheetah.OpenSearch.Configuration
    name: Configuration
    href: Cheetah.OpenSearch.Configuration.html
