---
- name: Cheetah.Kafka
  items:
    - name: latest
      href: Cheetah.Kafka/toc.yml
- name: Cheetah.OpenSearch
  items:
    - name: latest
      href: Cheetah.OpenSearch/toc.yml
      homepage: Cheetah.OpenSearch/index.md
- name: Cheetah.Auth
  items:
    - name: latest
      href: Cheetah.Auth/toc.yml
      homepage: Cheetah.Auth/index.md
