---
- name: Cheetah.Kafka
  items:
    - name: latest
      href: Cheetah.Kafka/toc.yml
- name: Cheetah.OpenSearch
  items:
    - name: latest
      href: Cheetah.OpenSearch/toc.yml
    - name: v1.1.0
      href: Cheetah.OpenSearch/v1.1.0/toc.yml
      homepage: Cheetah.OpenSearch/v1.1.0/index.md
- name: Cheetah.SchemaRegistry
  items:
    - name: latest
      href: Cheetah.SchemaRegistry/toc.yml
    - name: v2.1.0
      href: Cheetah.SchemaRegistry/v2.1.0/toc.yml
      homepage: Cheetah.SchemaRegistry/v2.1.0/index.md
