version: '3'
services: 
  example-component-test:
    build:
      context: ..
      dockerfile: Cheetah.ComponentTest.Test/Dockerfile
      args:
        # Nuget restore outside Visual Studio
        - GITHUB_ACTOR=${GITHUB_ACTOR:-Missing required GITHUB_ACTOR}
        - GITHUB_TOKEN=${GITHUB_TOKEN:-Missing required GITHUB_TOKEN}
    environment:
      KAFKA__URL: kafka:19093
      COMPONENTTEST__CONSUMERTOPIC: TestTopic
      COMPONENTTEST__PRODUCERTOPIC: TestTopic
      KAFKA__CLIENTID: ClientId
      KAFKA__CLIENTSECRET: 1234
        
networks:
  default:
    name: "cheetah-infrastructure"