---
version: '3'
services:
  example-component-test:
    build:
      context: ..
      dockerfile: Cheetah.ComponentTest.Test/Dockerfile
      secrets:
        - GITHUB_TOKEN
        - GITHUB_ACTOR
    environment:
      KAFKA__URL: kafka:19092
      COMPONENTTEST__CONSUMERTOPIC: TestTopic
      COMPONENTTEST__PRODUCERTOPIC: TestTopic
      KAFKA__CLIENTID: ClientId
      KAFKA__CLIENTSECRET: 1234

networks:
  default:
    name: "cheetah-infrastructure"

secrets:
  GITHUB_TOKEN:
    environment: GITHUB_TOKEN
  GITHUB_ACTOR:
    environment: GITHUB_ACTOR
