---
version: '3'
services:
  example-component-test-xunit:
    build:
      context: ..
      dockerfile: Cheetah.ComponentTest.XUnit/Dockerfile
      secrets:
        - GITHUB_TOKEN
        - GITHUB_ACTOR
    environment:
      KAFKA__URL: kafka:19092
      COMPONENTTEST__CONSUMERTOPIC: TestTopic
      COMPONENTTEST__PRODUCERTOPIC: TestTopic
      KAFKA__CLIENTID: myapp
      KAFKA__CLIENTSECRET: 1234
      KAFKA__AUTHENDPOINT: http://cheetahoauthsimulator:80/oauth2/token
      OPENSEARCH__CLIENTID: ClientId
      OPENSEARCH__CLIENTSECRET: 1234
      OPENSEARCH__AUTHENDPOINT: http://cheetahoauthsimulator:80/oauth2/token
      OPENSEARCH__URL: http://opensearch:9200
      KAFKA__SCHEMAREGISTRYURL: http://schema-registry:8080/apis/ccompat/v7

networks:
  default:
    name: "cheetah-infrastructure"

secrets:
  GITHUB_TOKEN:
    environment: GITHUB_TOKEN
  GITHUB_ACTOR:
    environment: GITHUB_ACTOR
