// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Cheetah.ComponentTest.Test.Model.Avro
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class AdvancedAvroObject : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""AdvancedAvroObject"",""namespace"":""Cheetah.ComponentTest.Test.Model.Avro"",""fields"":[{""name"":""Id"",""type"":""string""},{""name"":""Name"",""type"":""string""},{""name"":""AvroObjectWithEnum"",""type"":{""type"":""record"",""name"":""AvroObjectWithEnum"",""namespace"":""Cheetah.ComponentTest.Test.Model.Avro"",""fields"":[{""name"":""EnumType"",""type"":{""type"":""enum"",""name"":""EnumTypeAvro"",""namespace"":""Cheetah.ComponentTest.Test.Model.Avro"",""symbols"":[""EnumType1"",""EnumType2"",""EnumType3""]}},{""name"":""NullableInt"",""default"":null,""type"":[""null"",""int""]},{""name"":""NullableString"",""default"":null,""type"":[""null"",""string""]}]}},{""name"":""LongNumber"",""type"":""long""}]}");
		private string _Id;
		private string _Name;
		private AvroObjectWithEnum _AvroObjectWithEnum;
		private long _LongNumber;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return AdvancedAvroObject._SCHEMA;
			}
		}
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				this._Id = value;
			}
		}
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				this._Name = value;
			}
		}
		public AvroObjectWithEnum AvroObjectWithEnum
		{
			get
			{
				return this._AvroObjectWithEnum;
			}
			set
			{
				this._AvroObjectWithEnum = value;
			}
		}
		public long LongNumber
		{
			get
			{
				return this._LongNumber;
			}
			set
			{
				this._LongNumber = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Id;
			case 1: return this.Name;
			case 2: return this.AvroObjectWithEnum;
			case 3: return this.LongNumber;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Id = (System.String)fieldValue; break;
			case 1: this.Name = (System.String)fieldValue; break;
			case 2: this.AvroObjectWithEnum = (AvroObjectWithEnum)fieldValue; break;
			case 3: this.LongNumber = (System.Int64)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
