name: automerge

on:
  pull_request:

jobs:
  automerge:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: automerge for pull request
        if: ${{ github.actor == 'cheetahbot' }}
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: merge
          token: "${{ secrets.GITHUB_TOKEN }}"
