name: Test Cheetah.Shared NuGet Package

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  push:
    branches: [main]
    #paths: [src]
  pull_request:
    branches: [main, "release/**"]
    #paths: [src]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  dotnet-test:
    name: Dotnet Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dotnet test
        run: dotnet test --logger trx --filter 'TestType!=IntegrationTests' /nowarn:cs1591

      - name: Display test report
        uses: dorny/test-reporter@v1.6.0
        if: always()
        with:
          name: Tests
          path: src/Cheetah.WebApi.Shared.Test/TestResults/*.trx
          reporter: dotnet-trx

  should-run: # seperate step to support ci/cd status checks
    needs: dotnet-test
    runs-on: ubuntu-latest
    outputs:
      tag-check: ${{ steps.tag-check.outputs.value }}
      event-name-check: ${{ steps.event-name-check.outputs.value }}

    steps:
      # the pull request contains the 'e2e-test' label
      - name: Tag check
        id: tag-check
        if: ${{ contains(github.event.pull_request.labels.*.name, 'e2e-test') && !contains(github.event.pull_request.labels.*.name, 'blocked') }}
        run: echo "value=true" >> "$GITHUB_OUTPUT"

      # not started from a pull-request
      - name: Check for specific label
        id: event-name-check
        if: ${{github.event_name != 'pull_request'}}
        run: echo "value=true" >> "$GITHUB_OUTPUT"

  test-opensearch:
    name: Test OpenSearch
    needs: should-run
    runs-on: ubuntu-latest
    if: ${{ needs.should-run.outputs.event-name-check == 'true' || needs.should-run.outputs.tag-check == 'true' }}
    needs: dotnet-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup integration test
        uses: ./.github/actions/setup-integration-test
        with:
          PAT: ${{ secrets.PAT }}

      - name: Start development infrastructure
        working-directory: integrationtests/
        run: docker compose --profile opensearch --profile oauth up -d --build

      - name: Add hosts to /etc/hosts
        run: |
          sudo echo "127.0.0.1 opensearch" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 cheetahoauthsimulator" | sudo tee -a /etc/hosts

      - name: Wait for opensearch, the slowest component
        uses: nick-fields/retry@v2.9.0
        with:
          timeout_minutes: 3
          max_attempts: 25
          retry_wait_seconds: 5
          warning_on_retry: false
          command: 'curl -sS -X GET -H "Content-Type: application/json" http://admin:admin@opensearch:9200/_cat/indices'

      - name: Test OpenSearch
        run: dotnet test --logger trx --verbosity normal --filter 'Category=OpenSearch'

      - name: Display test report
        uses: dorny/test-reporter@v1.6.0
        if: always()
        with:
          name: Tests
          path: src/Cheetah.WebApi.Shared.Test/TestResults/*.trx
          reporter: dotnet-trx

  test-kafka-auth:
    name: Test Kafka Auth
    needs: should-run
    runs-on: ubuntu-latest
    if: ${{ needs.should-run.outputs.event-name-check == 'true' || needs.should-run.outputs.tag-check == 'true' }}
    needs: dotnet-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup integration test
        uses: ./.github/actions/setup-integration-test
        with:
          PAT: ${{ secrets.PAT }}

      - name: Start development infrastructure
        working-directory: integrationtests/
        run: docker compose --profile kafka --profile oauth up -d --build

      - name: Add hosts to /etc/hosts
        run: |
          sudo echo "127.0.0.1 kafka" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 cheetahoauthsimulator" | sudo tee -a /etc/hosts

      - name: Test Kafka auth
        run: dotnet test --logger trx --verbosity normal --filter 'Category=Kafka'

      - name: Display test report
        uses: dorny/test-reporter@v1.6.0
        if: always()
        with:
          name: Tests
          path: src/Cheetah.WebApi.Shared.Test/TestResults/*.trx
          reporter: dotnet-trx

  component-test:
    name: Run Component Tests
    needs: should-run
    runs-on: ubuntu-latest
    if: ${{ needs.should-run.outputs.event-name-check == 'true' || needs.should-run.outputs.tag-check == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup integration test
        uses: ./.github/actions/setup-integration-test
        with:
          PAT: ${{ secrets.PAT }}

      - name: Start development infrastructure
        working-directory: integrationtests/
        run: docker compose --profile kafka --profile oauth --profile opensearch --profile schemaregistry up -d --build

      - name: Run component tests
        working-directory: src/Cheetah.ComponentTest.XUnit
        run: docker compose -f docker-compose.yaml up --abort-on-container-exit
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
