name: Create and publish Cheetah.shared nuget package

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main

env:
  SOLUTION_PATH: ./Cheetah.WebApi.Shared.sln

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Setup .Net Core SDK 6.0"
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0"
        # Elastic is required for integration tests
      - name: Run ElasticSearch # This reuses the options from cheetah-example-processing's ES container
        run: docker run
          --detach
          -p 9200:9200
          -e "discovery.type=single-node"
          -e "bootstrap.memory_lock=true"
          -e "ES_JAVA_OPTS=-Xms2g -Xmx2g -Dlog4j2.formatMsgNoLookups"
          -e "xpack.security.enabled=false"
          -e "xpack.license.self_generated.type=basic"
          elasticsearch:8.4.1
      - name: "Dotnet build"
        run: dotnet build --configuration Release ${{ env.SOLUTION_PATH}}
      - name: "Test"
        run: dotnet test --no-restore --verbosity normal --filter 'FullyQualifiedName!~Integration' ${{ env.SOLUTION_PATH}}
      - name: "Test Integration"
        run: dotnet test --no-restore --verbosity normal --filter 'FullyQualifiedName~Integration' ${{ env.SOLUTION_PATH}}
