name: Create and publish Cheetah.shared nuget package

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main

env:
  SOLUTION_PATH: ./Cheetah.WebApi.Shared.sln

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Setup .Net Core SDK 6.0"
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0"
      - name: Run ElasticSearch
        run: docker run elasticsearch:8.4.1 --detach
      - name: "Dotnet build"
        run: dotnet build --configuration Release ${{ env.SOLUTION_PATH}}
      - name: "Test"
        run: dotnet test --no-restore --verbosity normal --filter 'FullyQualifiedName!~Integration' ${{ env.SOLUTION_PATH}}
      - name: "Test Integration"
        run: dotnet test --no-restore --verbosity normal --filter 'FullyQualifiedName~Integration' ${{ env.SOLUTION_PATH}}
