name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      project:
        description: Which project to create a release branch for
        required: true
        type: choice
        options:
          - Cheetah.Kafka
          - Cheetah.OpenSearch
          - Cheetah.SchemaRegistry
      bump-type:
        description: Increment major or minor semantic version on main branch after release branch has been created
        required: true
        type: choice
        options:
          - major
          - minor
        default: minor

jobs:
  get-csproj-filepath:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      csproj-filepath: ${{ steps.get-csproj-filepath.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        
      - name: Get csproj filepath
        id: get-csproj-filepath
        uses: trifork/cheetah-lib-shared-dotnet/.github/actions/get-from-map@main
        with:
          file-path: ./.github/csproj-filepaths.yaml
          key: ${{ inputs.project }}

  create-release-branch:
    needs: get-csproj-filepath
    uses: trifork/cheetah-lib-shared-dotnet/.github/workflows/dotnet-create-release-branch.yml@main
    with:
      project-name: ${{ inputs.project }}
      bump-type: ${{ inputs.bump-type }}
      csproj-filepath: ${{ needs.get-csproj-filepath.outputs.csproj-filepath }}
    secrets:
      GITHUB_PUSH_PAT: ${{ secrets.READ_PACKAGE_PAT }}
