name: Create Snapshot

on:
  workflow_dispatch:
    inputs:
      project:
        description: Which project to create a snapshot of
        required: true
        type: choice
        options:
          - Cheetah.OpenSearch
          - Cheetah.Kafka
          - Cheetah.SchemaRegistry
        default: Cheetah.OpenSearch

jobs:
  get-csproj-filepath:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      csproj-filepath: ${{ steps.get-csproj-filepath.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get csproj filepath
        id: get-csproj-filepath
        uses: trifork/cheetah-lib-shared-dotnet/.github/actions/get-from-map@main
        with:
          file-path: ./.github/csproj-filepaths.yaml
          key: ${{ inputs.project }}

  create-snapshot:
    needs: get-csproj-filepath
    uses: trifork/cheetah-lib-shared-dotnet/.github/workflows/dotnet-create-snapshot.yml@main
    with:
      fat-pack: true
      csproj-filepath: ${{ needs.get-csproj-filepath.outputs.csproj-filepath }}
    secrets:
      TRIFORK_GITHUB_PAT: ${{ secrets.WRITE_PACKAGE_PAT }}
