name: Create Snapshot

on:
  push:

jobs:
  create-snapshot:
    uses: trifork/cheetah-infrastructure-utils/.github/workflows/docker-create-snapshot.yml@main
    with:
      image-name: cheetah-example-alertservice
      context: src/Cheetah.Kafka.ExampleProcessor
    secrets:
      TRIFORK_GITHUB_PAT: ${{ secrets.WRITE_PACKAGE_PAT }}