name: Create and publish Cheetah.shared nuget package

on:
  workflow_dispatch:

  push:
    tags:
      - "v*"

env:
  PROJECT_PATH: ./src/Cheetah.WebApi.Shared/Cheetah.WebApi.Shared.csproj
  SOLUTION_PATH: ./Cheetah.WebApi.Shared.sln

jobs:
  build-and-push-nuget:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Setup .Net Core SDK 6.0"
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0"
      - name: "Dotnet build"
        run: dotnet build --configuration Release ${{ env.PROJECT_PATH}}
      - name: "Test"
        run: dotnet test --no-restore --verbosity normal ${{ env.SOLUTION_PATH}}
      - name: "create output-folder"
        run: mkdir -p output
      - name: Get Tag-name
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/v}
      - name: "package with version"
        if: startsWith(github.ref, 'refs/tags/v')
        run: dotnet pack -o output -c Release ${{ env.PROJECT_PATH}} /p:PackageVersion=${{ steps.vars.outputs.tag }}
      - name: "package with suffix"
        if: "!startsWith(github.ref, 'refs/tags/v')"
        run: dotnet pack --version-suffix ${{ github.run_number }} -o output -c Release ${{ env.PROJECT_PATH}}
      - name: "Prep Source"
        run: dotnet nuget add Source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/trifork/index.json"
      - name: "Publish to github packages"
        run: dotnet nuget push output/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
