name: Create and publish Cheetah.shared nuget package

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
  push:
    tags:
      - "v*"

env:
  PROJECT_PATH: ./src/Cheetah.WebApi.Shared/Cheetah.WebApi.Shared.csproj

jobs:
  build-and-push-nuget:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "dotnet publish"
        uses: trifork/cheetah-infrastructure-utils/.github/actions/nuget-publish@main
        with:
          project_filepath: ${{ env.PROJECT_PATH }}
          dotnet-version: "6.0"
          package_name: "Cheetah.WebApi.Shared"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          releasenotes_path: src/Cheetah.WebApi.Shared/ReleaseNotes.md
          kamstrup_gitlab_token: ${{ vars.KAMSTRUP_GITLAB_TOKEN }}
