name: Create Release

on:
  workflow_dispatch:

jobs:
  run-tests:
    uses: ./.github/workflows/e2e.yml
    secrets:
      PAT: ${{ secrets.READ_PACKAGE_PAT }}

  get-csproj-filepath:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: run-tests
    outputs:
      project-name: ${{ steps.get-project-name.outputs.project-name }}
      csproj-filepath: ${{ steps.get-csproj-filepath.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get project name
        id: get-project-name
        run: |
          ref_name=${{ github.ref_name }}
          project_name_and_version=${ref_name#release/}
          project_name=${project_name_and_version%*-v*}
          echo "project-name=$project_name" >> $GITHUB_OUTPUT

      - name: Get csproj filepath
        id: get-csproj-filepath
        uses: trifork/cheetah-infrastructure-utils/.github/actions/get-from-map@main
        with:
          file-path: ./.github/csproj-filepaths.yaml
          key: ${{ steps.get-project-name.outputs.project-name }}

  create-release:
    needs: get-csproj-filepath
    uses: trifork/cheetah-infrastructure-utils/.github/workflows/dotnet-create-release.yml@main
    with:
      project-name: ${{ needs.get-csproj-filepath.outputs.project-name }}
      fat-pack: true
      csproj-filepath: ${{ needs.get-csproj-filepath.outputs.csproj-filepath }}
    secrets:
      TRIFORK_GITHUB_PAT: ${{ secrets.WRITE_PACKAGE_PAT }}
      KAMSTRUP_GITLAB_PAT: ${{ secrets.KAMSTRUP_GITLAB_PAT }}
