name: Publish docfx

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - .NET Create Release
    types:
      - completed

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write



jobs:
  publish-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "dotnet build"
        uses: trifork/cheetah-infrastructure-utils/.github/actions/dotnet/dotnet-build@main

      - name: Build docfx
        uses: trifork/cheetah-infrastructure-utils/.github/actions/docfx/docfx-build@main

      - name: Get csproj filepath
        id: get-csproj-filepath
        uses: trifork/cheetah-infrastructure-utils/.github/actions/get-from-map@main
        with:
          file-path: ./.github/csproj-filepaths.yaml
          key: ${{github.repository}}

      - name: Get project version
        id: get-version
        uses: trifork/cheetah-infrastructure-utils-workflows/.github/actions/versioning/get-version@main
        with:
          file-path: ${{ steps.get-csproj-filepath.outputs.value }}
          prefix: "<VersionPrefix>"
          suffix: "</VersionPrefix>"

      - name: create public/
        run: |
          mkdir -p public/
          mv docs/ public/_source
          mv src/ public/src
          mv .gitignore public/.gitignore
          rm public/_source/api/.gitignore
          mv _site/ public/docs

      - name: echo variables for gh pages
        run: |
          echo "version: ${{ steps.get-version.outputs.version }}"
          echo "repo: ${{ github.repository }}"
          echo "destination: v${{ steps.get-version.outputs.version }}"


