name: Pusblish docfx

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - .NET Create Release
    types:
      - completed

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "dotnet build"
        uses: trifork/cheetah-infrastructure-utils/.github/actions/dotnet/dotnet-build@main
      
      - name: Build docfx
        uses: trifork/cheetah-infrastructure-utils/.github/actions/docfx/docfx-build@main

      - name: create public/
        run: |
          mkdir -p public/
          mv docs/ public/_source
          mv src/ public/src
          mv .gitignore public/.gitignore
          rm public/_source/api/.gitignore
          mv _site/ public/docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          exclude_assets: ""
          force_orphan: true
      
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.READ_PACKAGE_PAT }}
          repository: trifork/cheetah-artifact-documentation
          event-type: docs-update
