name: Build docfx

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - .NET Create Release Branch
      - .NET Create Release Candidate
    types:
      - completed

env:
  SOLUTION_FILEPATH: ./Cheetah.WebApi.Shared.sln

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "dotnet build"
        uses: trifork/cheetah-infrastructure-utils/.github/actions/dotnet/dotnet-build@main
      
      - name: Build docfx
        uses: trifork/cheetah-infrastructure-utils/.github/actions/docfx/docfx-build@main