name: Build docfx

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - .NET Create Release Branch
      - .NET Create Release Candidate
    types:
      - completed

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: "dotnet build"
        uses: trifork/cheetah-infrastructure-utils/.github/actions/dotnet/dotnet-build@main
      
      - name: Build docfx
        uses: trifork/cheetah-infrastructure-utils/.github/actions/docfx/docfx-build@main