name: docs

on:
  pull_request:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  SOLUTION_FILEPATH: ./Cheetah.WebApi.Shared.sln

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "dotnet build"
        uses: trifork/cheetah-infrastructure-utils/.github/actions/build-dotnet@main
        with:
          read_package_pat: ${{ secrets.PACKAGE_PAT }} # we need this, as GITHUB_TOKEN only have permission to its own repo
          project_path: ${{ env.PROJECT_PATH }}
          dotnet-version: "6.0"
          github_actor: ${{ github.actor }}
          solution_filepath: ${{ env.SOLUTION_FILEPATH }}

      - run: dotnet tool update -g docfx

      - run: docfx metadata --logLevel verbose docs/docfx.json
      - run: docfx build --warningsAsErrors docs/docfx.json
