name: .NET Create Release Candidate

on:
  push:
    branches:
      - "release/**"

jobs:
  create-release-candidate:
    uses: trifork/cheetah-infrastructure-utils/.github/workflows/dotnet-create-release-candidate.yml@main
    with:
      csproj-filepath: cheetah-dotnet-release-test.csproj
    secrets:
      PAT: ${{ secrets.PACKAGE_PAT }}