name: .NET Create Release Candidate WebApi

on:
  push:
    branches:
      - "release/**"

jobs:
  create-release-candidate:
    uses: trifork/cheetah-infrastructure-utils/.github/workflows/dotnet-create-release-candidate.yml@main
    with:
      fat-pack: true
      csproj-filepath: src/Cheetah.WebApi.Shared/Cheetah.WebApi.Shared.csproj
    secrets:
      PAT: ${{ secrets.PACKAGE_PAT }}