name: .NET Create Snapshot

on:
  workflow_dispatch:
    inputs:
      project:
        description: Which project to create a snapshot of
        required: true
        type: choice
        options:
          - Cheetah.WebApi.Shared
          - Cheetah.ComponentTest
        default: Cheetah.WebApi.Shared

jobs:
  get-csproj-filepath:
    runs-on: ubuntu-latest
    outputs:
      csproj-filepath: ${{ steps.get-csproj-filepath.outputs.csproj-filepath }}
    steps:
      - name: Get csproj filepath
        id: get-csproj-filepath
        uses: ./.github/workflows/actions/get-csproj-filepath
        with:
          project-name: ${{ inputs.project }}

  create-snapshot:
    needs: get-csproj-filepath
    uses: trifork/cheetah-infrastructure-utils/.github/workflows/dotnet-create-snapshot.yml@main
    with:
      fat-pack: true
      csproj-filepath: ${{ needs.get-csproj-filepath.outputs.csproj-filepath }}
    secrets:
      PAT: ${{ secrets.PAT }}