name: E2E

on:
  workflow_call:
    secrets:
      PAT:
        description: A personal access token with permission to publish a package and push to all branches
        required: true
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  push:
    branches: [ 'main', 'release/v**' ]
  pull_request:
    branches: [ 'main', 'release/v**' ]
    types: [ opened, synchronize, reopened, labeled ]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  should-run:
    uses: trifork/cheetah-infrastructure-utils-workflows/.github/workflows/e2e-should-run.yml@main

  dotnet-test:
    needs: should-run
    if: ${{ needs.should-run.outputs.should-run }}

    name: Dotnet Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup development infrastructure
        uses: ./.github/actions/setup-development-infrastructure
        with:
          PAT: ${{ secrets.PAT }}

      - name: Start development infrastructure
        working-directory: integrationtests/
        run: docker compose --profile core up -d --quiet-pull

      - name: Wait for opensearch, the slowest component
        uses: nick-fields/retry@v2.9.0
        with:
          timeout_minutes: 3
          max_attempts: 25
          retry_wait_seconds: 5
          warning_on_retry: false
          command: 'curl -sS -X GET -H "Content-Type: application/json" http://admin:admin@localhost:9200/_cat/indices'

      - name: Dotnet Test
        run: dotnet test --logger trx

      - name: Display test report OpenSearch
        uses: dorny/test-reporter@v1.7.0
        if: always()
        with:
          name: Tests
          path: src/Cheetah.OpenSearch.Test/TestResults/*.trx
          reporter: dotnet-trx

      - name: Display test report Kafka
        uses: dorny/test-reporter@v1.7.0
        if: always()
        with:
          name: Tests
          path: src/Cheetah.Kafka.Test/TestResults/*.trx
          reporter: dotnet-trx