name: sbom

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: docker run --rm -v /tmp:/tmp -v $(pwd):/app:rw -e FETCH_LICENSE=true -t ghcr.io/cyclonedx/cdxgen -r /app/src -o /app/sbom.json -t dotnet
      - name: Commit the sbom files
        uses: EndBug/add-and-commit@v7
        with:
          # This makes the GH Actions user/bot the author of the commit
          default_author: github_actor
          message: "Automatically update sbom files"
          add: "*.json"
