name: Create and publish Cheetah.shared nuget package

on:
  workflow_dispatch:

  push:
    branches: ["main"]
    tags:
      - "v*"

env:
  PROJECT_PATH: ./src/Cheetah.WebApi.Shared/Cheetah.WebApi.Shared.csproj
  SOLUTION_FILEPATH: ./Cheetah.WebApi.Shared.sln

jobs:
  build-and-push-nuget:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "dotnet build"
        uses: trifork/cheetah-infrastructure-utils/.github/actions/build-dotnet@main
        with:
          read_package_pat: ${{ secrets.PACKAGE_PAT }} # we need this, as GITHUB_TOKEN only have permission to its own repo
          project_path: ${{ env.PROJECT_PATH }}
          dotnet-version: "6.0"
          github_actor: ${{ github.actor }}
          solution_filepath: ${{ env.SOLUTION_FILEPATH }}
      - name: "create output-folder"
        run: mkdir -p output
      - name: Get Tag-name
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/v}
      - name: "package with version"
        if: startsWith(github.ref, 'refs/tags/v')
        run: dotnet pack -o output -c Release ${{ env.PROJECT_PATH}} /p:PackageVersion=${{ steps.vars.outputs.tag }}
      - name: "package with suffix"
        if: "!startsWith(github.ref, 'refs/tags/v')"
        run: dotnet pack --version-suffix ${{ github.run_number }} -o output -c Release ${{ env.PROJECT_PATH}}
      - name: "Prep Source"
        run: dotnet nuget add Source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/trifork/index.json"
      - name: "Publish to github packages"
        run: dotnet nuget push output/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
