name: Create and publish Cheetah.shared nuget package

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: ["main"]
    tags:
      - "v*"

env:
  PROJECT_PATH: ./src/Cheetah.WebApi.Shared/Cheetah.WebApi.Shared.csproj
  SOLUTION_FILEPATH: ./Cheetah.WebApi.Shared.sln

jobs:
  build-and-push-nuget:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "dotnet build"
        uses: trifork/cheetah-infrastructure-utils/.github/actions/build-dotnet@main
        with:
          read_package_pat: ${{ secrets.PACKAGE_PAT }} # we need this, as GITHUB_TOKEN only have permission to its own repo
          project_path: ${{ env.PROJECT_PATH }}
          dotnet-version: "6.0"
          github_actor: ${{ github.actor }}
          solution_filepath: ${{ env.SOLUTION_FILEPATH }}
      - name: "create output-folder"
        run: mkdir -p output
      - name: "dotnet publish"
        #uses: trifork/cheetah-infrastructure-utils/.github/actions/build-dotnet@main
        uses: "./.github/actions/publishnuget"
        with:
          project_filepath: ${{ env.PROJECT_PATH }}
          dotnet-version: "6.0"
          package_name: "Cheetah.WebApi.Shared"
          github_token: ${{ secrets.GITHUB_TOKEN }}
