name: update documentation

on:
  push:
    branches:
      - main

jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - { name: Cheetah.Kafka, toc_file: ".github/toc-files/articles/toc.yml" }
          - { name: Cheetah.OpenSearch, toc_file: ".github/toc-files/articles/toc.yml" }
        #  - { name: Cheetah.SchemaRegistry, toc_file: ".github/toc-files/articles/toc.yml" }
        #  - { name: Cheetah.Kafka, toc_file: ".github/toc-files/api/toc.yml" }
        #  - { name: Cheetah.OpenSearch, toc_file: ".github/toc-files/api/toc.yml" }
        #  - { name: Cheetah.Auth, toc_file: ".github/toc-files/api/toc.yml" }
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if files have changed
        id: changed-files
        uses: tj-actions/changed-files@v45
        with: 
          dir_names: "true"
          files: |
            doc/api/${{ matrix.project.name }}/**
            doc/articles/${{ matrix.project.name }}/**

      - name: Exho output variable
        run: |
          echo "any_changed=${{ steps.changed-files.outputs.any_changed }}"
          echo "project=${{ matrix.project.name }}"
          echo all_changed_files_count ${{ steps.changed-files.outputs.all_changed_files_count }}
          echo any_modified ${{ steps.changed-files.outputs.any_modified }}
          echo modifede_files_count ${{ steps.changed-files.outputs.modified_files_count }}
          echo only_changed ${{ steps.changed-files.outputs.only_changed }}
          echo only_modified ${{ steps.changed-files.outputs.only_modified }}
          


      - name: Set output variable
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        run: |
          echo "changed=true" >> $GITHUB_ENV
          echo "changed_project=${{ matrix.project.name }}" >> $GITHUB_ENV
          echo "changed_file=${{ matrix.project.toc_file }}" >> $GITHUB_ENV

  update-doc:
    uses: kasttrifork/cheetah-lib-shared-dotnet/.github/workflows/docfx-publish.yml@main
    if: ${{ needs.check-for-changes.outputs.changed == 'true' }}
    with:
      project: 'Cheetah.Kafka'
      file: ".github/toc-files/articles/toc.yml"