name: Update documentation

on:
  push:
    branches:
      - main

jobs:
  api-Cheetah-Kafka:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if files have changed
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          dir_names: "true"
          files: |
            docs/api/Cheetah.Kafka/*.md

      - name: Set output variable
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        run: |
          echo "changed=true" >> $GITHUB_ENV
    outputs:
      changed: ${{ steps.changed-files.outputs.any_changed }}

  update-doc-api-Cheetah-Kafka:
    if: ${{ needs.api-Cheetah-Kafka.outputs.changed == 'true' }}
    needs: api-Cheetah-Kafka
    uses: trifork/cheetah-lib-shared-dotnet/.github/workflows/docfx-publish.yml@main
    with:
      project: Cheetah.Kafka
      file: .github/toc-files/api/toc.yml
    secrets:
      WRITE_PACKAGE_PAT: ${{ secrets.WRITE_PACKAGE_PAT }}

  api-Cheetah-Auth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if files have changed
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          dir_names: "true"
          files: |
            docs/api/Cheetah.Auth/*.md

      - name: Set output variable
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        run: |
          echo "changed=true" >> $GITHUB_ENV
    outputs:
      changed: ${{ steps.changed-files.outputs.any_changed }}

  update-doc-api-Cheetah-Auth:
    if: ${{ needs.api-Cheetah-Auth.outputs.changed == 'true' }}
    needs: api-Cheetah-Auth
    uses: trifork/cheetah-lib-shared-dotnet/.github/workflows/docfx-publish.yml@main
    with:
      project: Cheetah.Auth
      file: .github/toc-files/api/toc.yml
    secrets:
      WRITE_PACKAGE_PAT: ${{ secrets.WRITE_PACKAGE_PAT }}

  api-Cheetah-OpenSearch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if files have changed
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          dir_names: "true"
          files: |
            docs/api/Cheetah.OpenSearch/*.md

      - name: Set output variable
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        run: |
          echo "changed=true" >> $GITHUB_ENV
    outputs:
      changed: ${{ steps.changed-files.outputs.any_changed }}

  update-doc-api-Cheetah-OpenSearch:
    if: ${{ needs.api-Cheetah-OpenSearch.outputs.changed == 'true' }}
    needs: api-Cheetah-OpenSearch
    uses: trifork/cheetah-lib-shared-dotnet/.github/workflows/docfx-publish.yml@main
    with:
      project: Cheetah.OpenSearch
      file: .github/toc-files/api/toc.yml
    secrets:
      WRITE_PACKAGE_PAT: ${{ secrets.WRITE_PACKAGE_PAT }}

  articles-Cheetah-Kafka:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Check if files have changed
          id: changed-files
          uses: tj-actions/changed-files@v45
          with:
            dir_names: "true"
            files: |
              docs/articles/Cheetah.Kafka/*.md

        - name: Set output variable
          if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
          run: |
            echo "changed=true" >> $GITHUB_ENV
      outputs:
        changed: ${{ steps.changed-files.outputs.any_changed }}

  update-doc-articles-Cheetah-Kafka:
    if: ${{ needs.articles-Cheetah-Kafka.outputs.changed == 'true' }}
    needs: articles-Cheetah-Kafka
    uses: trifork/cheetah-lib-shared-dotnet/.github/workflows/docfx-publish.yml@main
    with:
      project: Cheetah.Kafka
      file: .github/toc-files/articles/toc.yml
    secrets:
      WRITE_PACKAGE_PAT: ${{ secrets.WRITE_PACKAGE_PAT }}

  articles-Cheetah-OpenSearch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if files have changed
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          dir_names: "true"
          files: |
            docs/articles/Cheetah.OpenSearch/*.md

      - name: Set output variable
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        run: |
          echo "changed=true" >> $GITHUB_ENV
    outputs:
      changed: ${{ steps.changed-files.outputs.any_changed }}

  update-articles-Cheetah-OpenSearch:
    if: ${{ needs.articles-Cheetah-OpenSearch.outputs.changed == 'true' }}
    needs: articles-Cheetah-OpenSearch
    uses: trifork/cheetah-lib-shared-dotnet/.github/workflows/docfx-publish.yml@main
    with:
      project: Cheetah.OpenSearch
      file: .github/toc-files/articles/toc.yml
    secrets:
      WRITE_PACKAGE_PAT: ${{ secrets.WRITE_PACKAGE_PAT }}

  articles-Cheetah-SchemaRegistry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if files have changed
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          dir_names: "true"
          files: |
            docs/articles/Cheetah.SchemaRegistry/*.md

      - name: Set output variable
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        run: |
          echo "changed=true" >> $GITHUB_ENV
    outputs:
      changed: ${{ steps.changed-files.outputs.any_changed }}

  update-articles-Cheetah-SchemaRegistry:
    if: ${{ needs.articles-Cheetah-SchemaRegistry.outputs.changed == 'true' }}
    needs: articles-Cheetah-SchemaRegistry
    uses: trifork/cheetah-lib-shared-dotnet/.github/workflows/docfx-publish.yml@main
    with:
      project: Cheetah.SchemaRegistry
      file: .github/toc-files/articles/toc.yml
    secrets:
      WRITE_PACKAGE_PAT: ${{ secrets.WRITE_PACKAGE_PAT }}