name: update documenation

on:
  push:
    branches:
      - main

jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - { name: Cheetah.Kafka, toc_file: ".github/toc-files/articles/toc.yml" }
          - { name: Cheetah.OpenSearch, toc_file: ".github/toc-files/articles/toc.yml" }
        #  - { name: Cheetah.SchemaRegistry, toc_file: ".github/toc-files/articles/toc.yml" }
        #  - { name: Cheetah.Kafka, toc_file: ".github/toc-files/api/toc.yml" }
        #  - { name: Cheetah.OpenSearch, toc_file: ".github/toc-files/api/toc.yml" }
        #  - { name: Cheetah.Auth, toc_file: ".github/toc-files/api/toc.yml" }
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if files have changed
        uses: tj-actions/changed-files@v45
        id: changed-files
        with: 
          files: |
            doc/api/${{ matrix.project.name }}/**
            doc/articles/${{ matrix.project.name }}/**

      - name: Set output variable
        if: ${{steps.changed-files.outputs.any_changed == 'true'}}
        run: echo "changed=true" >> $GITHUB_ENV

  update-doc:
    runs-on: ubuntu-latest
    needs: check-for-changes
    if: ${{ env.changed == 'true' }}
    steps: 

    - name: update docs
      uses: kasttrifork/cheetah-lib-shared-dotnet/.github/workflows/docfx-publish@main
      with:
        toc-file: ${{ matrix.project.toc_file }}
        project: ${{ matrix.project.name }}
