name: Get csproj filepath
description: Gets the path to the .csproj file for the given project. This is specific for this repository

inputs:
  project-name:
    description: The name of the project. Should be either Cheetah.WebApi.Shared or Cheetah.ComponentTest
    required: true
outputs:
  csproj-filepath:
    description: The path to the .csproj file
    value: ${{ steps.get-csproj-filepath.outputs.csproj-filepath }}

runs:
  using: composite
  steps:
    - name: Get csproj filepath
      id: get-csproj-filepath
      shell: bash
      run: echo "csproj-filepath=$(grep -Po '(?<=${{ inputs.project-name }}:).*' ${{ github.action_path }}/csproj-filepaths.yaml | awk '{$1=$1};1')" >> $GITHUB_OUTPUT # Magic for retrieving the value of the given key in csproj-filepaths.yaml. The AWK command trims leading and trailing whitespaces